services:
  node-app:
    build:
      context: .
      dockerfile: docker/node-js-24/Dockerfile

    working_dir: /workspace

    ports:
      - "9701:9701"
      - "9801:9801"

    volumes:
      - ./project:/workspace

    command: sh -c "if [ ! -d node_modules ]; then npm install; fi && npm run dev-debug"
    # command: sh -c "if [ ! -d node_modules ]; then npm install; fi && npm run dev"
    # command: sh -c "if [ ! -d node_modules ]; then npm install; fi && npm run start"